version: '3.1'

services:
  chat-application:
    image: chat-application
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    deploy:
      replicas: 1
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://piyush1:cdkghArXO5WSj1ov@cluster0.zzkbr72.mongodb.net/
      - HTTP_PORT=5001
